### ISSUE TITLE
Support for v1 and v2 cplds

### ISSUE THREAD

**Issue by IanSB** [hoglet67/RGBtoHDMI#120]
Now we have separate folders for the different cplds, if you want to keep support for v1 and v2 versions in the field you could extend the bbc driver to detect those earlier versions and change the driver name to bbcv1 bbcv2 etc so they would then have their own profiles folders. (Those profiles differ from later versions)

**Comment by hoglet67** [comment]
Yes, I was also thinking we should do this.

For the pre-6.x CPLD I was thinking we would only include an Atom and a Beeb profile, to so it's not a pain to maintain.

One reason I checked in every BBC CPLD version was to confirm the version numbers where h_offset needs to change by a large amount.  I have this written down somewhere now.

I need to do the same with the Atom.

I'm actually quite keen to do this, as people are very reluctant to upgrade.

Dave

**Comment by IanSB** [comment]
I've just changed the code to hide the geometry menu's deprecated pixel sampling option in rgb/analog/yuv modes. It's still available in bbc mode but that could be modified further so it's only visible in bbcv1 and bbcv2 modes if you want to make the above changes.

**Comment by IanSB** [comment]
This has been addressed in the latest release 
https://github.com/hoglet67/RGBtoHDMI/releases/tag/20200504_d19df1c
