### ISSUE TITLE
Spectrum Regression

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#127]
Ian,

I've just setup the Spectrum again, and I'm seeing very poor results, much worse than before.

In particular, the DAC-C (RB/UV Hi) adjustment is now very narrow.

I've been testing with CPLD v6.1 so that I can work out when this started. In each case, I'm rebuilding the kernel, deleting the old Profiles and Palettes and copying new kernel and Profiles. So it should be a fresh start each time. There are no Saved Profiles.

The last commit which works well is: d45d2e5d

I can vary DAC-C from 172 to 186 and the picture stays stable.

Skipping forward two commits to: dc13e0f9 it's much worse.

The good range of DAC-C is now just 185-186.

(I can go back and to between these commits and it's very consistent)

The work that was done between those commits is some minor Profile tweaks and adding the User Defined Palettes.

So I think this is a Palette Issue.

It is possible the Spectrum 48K 9-Colour Palette got changed somehow in this process? It seems to have lost some of it's noise masking properties.

(I'm at a loss to think of any other explanation.....)

**Comment by IanSB** [comment]
I changed the Spectrum palette slightly to increase the overlap which improved noise immunity slightly for me but I guess not for you so I've reverted that change.

**Comment by hoglet67** [comment]
Thanks for looking at this - it's fixed the problem.
