### ISSUE TITLE
Eliminate fixed delay from YUV CPLD

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#132]
I've committed some code for testing to a branch called yuv80

This contains a new version of the YUV CPLD that replaces the large fixed delay with a smaller programmable delay.

Would you mind giving this a try on your Spectrum (which has a worse glitching than mine)? It's quite possible there will be problems.

You'll need to:
- rebuild the kernel to get the new cpld_yuv code
- update your spectrum profle (this just changes the value of HOFFSET)
- reprograme the CPLD with version 8.0

The CPLD works a bit differently now:
- counter has been reduced from 10 bits to 7 bits
- offset has been increased from 5 bits to 7 bits 
- the Edge setting controls which edge of HSYNC loads the counter (with offset)
- otherwise, the counter is free-running
- PSYNC is stopped on the trailing edge of HSYNC
- PSYNC is restarted when the counter expires

To ensure the software correctly synchronises to the first edge of PSYNC, there is still a need for a small delay between the trailing edge of HSYNC and the first edge of PSYNC. [ Edit: We really need to try to quantify this]

If this delay is too short, then you get lines shifted by whole quads. Here's a couple of examples:

![capture6](https://user-images.githubusercontent.com/1951463/72097788-0df96780-3315-11ea-9eeb-ceb40fe06578.png)

![capture0](https://user-images.githubusercontent.com/1951463/72099433-831a6c00-3318-11ea-99f4-98bb7e683789.png)

This can in theory occur when the reference Edge is either Leading or Trailing, but I'm only actually seeing it when edge is leading.

I'm seeing this at when Edge=Leading and Delay=14/Offset 0 or Delay=15/Offset = 7 (which I think are actually adjacent, due to the way the delay is inverted by the driver.

I've made this delay programmable, by extended the hardware "offset" value from from 5 bits to 7 bits.

There are no new parameters in the profile, but the 0-15 delay is now completely implemented in hardware.

I do need to draw out a pipeline diagram of this design, because if I ever have to look at it again in the future, it's not immediately obvious why we need HS4 and HS5.

Dave

**Comment by IanSB** [comment]
I tested this on my spectrum and I'm seeing the following:

No glitching with trailing edge in all possible offset and delay combinations

Glitching the same as above with leading edge when delay = 14 and offset = 0 to 4 also when delay=15 and offset = 7

Does this need to be tested with any other computers?

**Comment by hoglet67** [comment]
It might be worth testing your UK101.

As the delay has changed, the current DELAY and HOFFSET values in the profiles will need adjusting. This is probaby deterministic if I think about it a bit. I'll apply myself to this tomorrow.

Dave

**Comment by hoglet67** [comment]
I've just pushed a v8.1 that fixed a hang if the sync threshold was out of range (i.e. v8.0 re-introduced the the same bug we had before).

I've also updated the YUV Profiles, increasing HOFFSET by 16 in each case. I've tested the Atom, Spectrum and Superboard Profiles. All seem fine.

Dave

**Comment by hoglet67** [comment]
Closing for now, please re-open if I've broken anything....
