### ISSUE TITLE
Problems with old BBC cpld versions

### ISSUE THREAD

**Issue by IanSB** [hoglet67/RGBtoHDMI#139]
Testing on a Master 128

I'm getting really bad glitches with CPLD v2.3 in mode 0:
![capture5](https://user-images.githubusercontent.com/45300594/73946866-817b9e00-48ee-11ea-85c8-37441f1ab161.png)
They seem to be jumping 1 mode0 char / 8 pixels

The horizontal position of the v24 profile in mode 0 is wrong

V30 to V50 show no image at all with very unresponsive menu operation in all modes
V60 to V63 have vertical jumping in mode 7

Also the v30-v62 profile has wrong horizontal offsets for all modes

I think these were all working when I did the initial split into BBC and OBBC

**Comment by hoglet67** [comment]
This is with a Pi Zero?

And with a clean SD card + a release.sh build?

**Comment by hoglet67** [comment]
I've just done release.sh build, wiped my SD card, and reinstalled.

I can't reproduce any of these issues.

Dave

**Comment by IanSB** [comment]
OK I think I figured out the problem:

 I'm using an early 6 bit board which can only run the 3 bit firmware. That behaves itself with current firmware but older firmware inverts the sync when the field sync input is low which it is by default on the 6 bit board. The 3 bit board has field sync high by default. so the sync is getting inverted on a number of old firmware builds with the 6 bit board.
I should be able to fix it by tying the field sync input high.

**Comment by IanSB** [comment]
Tying vsync high has fixed it.

**Comment by hoglet67** [comment]
Phew!
