### ISSUE TITLE
MDA/EGA support?

### ISSUE THREAD

**Issue by andreacampanella** [hoglet67/RGBtoHDMI#171]
I would like to know how difficult wold it be to support MDA, it's just two bits, h+v and it's ttl, at the moment the only reasonable converter it's 80 dollars and MDA display are rare. 

https://en.wikipedia.org/wiki/IBM_Monochrome_Display_Adapter

**Comment by IanSB** [comment]
MDA is already supported in the standard PC profile.

**Comment by andreacampanella** [comment]
Where do I find documentation for it?

**Comment by IanSB** [comment]
The cable connections for MDA/CGA/EGA are mentioned in the Cables section:
https://github.com/hoglet67/RGBtoHDMI/wiki/Cables

I've also added a separate supported computers list to make it easier to find as they were listed in the quick start guide:
https://github.com/hoglet67/RGBtoHDMI/wiki/Supported-Computers
