### ISSUE TITLE
Additional GPIO Ports - Help for higher bitplanes?

### ISSUE THREAD

**Issue by dlasher** [hoglet67/RGBtoHDMI#187]
Would something like this : https://www.robotshop.com/en/io-hat-raspberry-pi-zero.html

help with the amiga's with higher bitplanes (like A1200/A4000) ?

**Comment by abrugsch** [comment]
I'm going to posit that the bandwidth on these parts is going to be a limiting factor. I2C on a pi operates in the KHz range (MCP23017's run the I2C bus at 400KHz or 1.7 MHz but the Pi zero can only drive them reliably at 400K IIRC) and it's a serial protocol so you're only clocking at best 1 byte of data at 50KHz (with no protocol overhead so it's even less.) there are SPI variants, but in my experiments the data rate still won't be anywhere near the data rate that would be needed for Amiga AGA. it's also been said many times that limiting bottleneck is the processing power of the Pi Zero, with it only just being able to manage the OCS/ECS 12-bit colour
