### ISSUE TITLE
Firmware recovery menu doesn't support single button mode

### ISSUE THREAD

**Issue by LinuxJedi** [hoglet67/RGBtoHDMI#198]
It appears on first boot recovery menu single_button_mode is ignored in Profiles/Default.txt (I don't think the file is read yet). If I patch the code so that single_button_mode is the default holding the button down just pauses and then cycles options instead of selecting as expected.

**Comment by IanSB** [comment]
Fixed in this release:

https://github.com/hoglet67/RGBtoHDMI/releases/tag/20210529_777ea4f
