### ISSUE TITLE
FF OSD - whole screen is dimmed

### ISSUE THREAD

**Issue by solarmon** [hoglet67/RGBtoHDMI#204]
Question for @IanSB regarding the FF OSD display. At the moment the whole screen is dimmed when FF OSD is displayed.

Can this behaviour be changed so that it only has a dimmed border around the FF OSD text - just like when it is displayed via the normal RGB output.

**Comment by IanSB** [comment]
@solarmon 

Unfortunately not, the FF OSD output is tri state: low = Black Border, High = FFOSD Text and floating = Amiga video
The FF_OSD input on RGBtoHDMI can only detect high and low so it treats High = FFOSD text and Low = Amiga video but also when Amiga video is detected it dims the whole screen to make the text easy to read. I did try not dimming the screen but you couldn't read the text on many backgrounds such as the boot screen.
