### ISSUE TITLE
Amiga 2000 CPLD Calibration Problem

### ISSUE THREAD

**Issue by ILAHWWINC** [hoglet67/RGBtoHDMI#208]
With my A2000 CPLD board and firmware beta25 i have flickering screen in hires interlaced screenmode. 

I can fix this using the auto calibration (save settings afterwards) and get a perfect picture. But after reset / power cycle the picture is flickering again. 

From this situation a reboot of the RGB2HDMI with the option in the settings 
removes the flickering.

What should i do to get a flickerfree screen without rebooting?

**Comment by IanSB** [comment]
Can you use the save log option when you have the flicker and also when it is OK and post both log.txt files. Also a screencap of the problem would be useful.

**Comment by IanSB** [comment]
I found a possible cause but as I don't have any suitable hardware I can't test it so please try the attached file:
[kernelrpi-interlace-change.zip](https://github.com/hoglet67/RGBtoHDMI/files/6527299/kernelrpi-interlace-change.zip)
Unzip and overwrite the existing kernel file on the SD card and reboot the Pi zero

**Comment by ILAHWWINC** [comment]
@IanSB 
This kernal works for me :-). Many thanks.

**Comment by IanSB** [comment]
@ILAHWWINC 

That change has been incorporated into the latest beta 27:
https://github.com/IanSB/RGBtoHDMI/releases

**Comment by ILAHWWINC** [comment]
Very fast help. Problem solved.

**Comment by LinuxJedi** [comment]
Can confirm this fixed the same issue for another user of my A2000 boards.
