### ISSUE TITLE
Atari STe color swapped

### ISSUE THREAD

**Issue by pixelk0** [hoglet67/RGBtoHDMI#216]
Hello and first, thank you. I already posted about some trial and errors on the ST Thread from [ c0pperdragon /
Amiga-Digital-Video ](https://github.com/c0pperdragon/Amiga-Digital-Video/issues/6).

I now have a perfectly stable image (needed to run the auto-calibration) but I have spotted a problem in the colour handling.

First it may be an error while soldering the 12 bits inputs, but the consistency in my error seems strange, it's as if some bits are swapped for all 3 RGB channels. A colour with a higher value is darker than the precedent, but it only happens in one in two colour.

Maybe it will be clearer with a few screenshots (I noticied it first trying some demos, then deluxe paint and degas elite)

![20210630090244](https://user-images.githubusercontent.com/5732483/123918191-e9b79d80-d983-11eb-9bb8-e55746951024.png)
![20210630090248](https://user-images.githubusercontent.com/5732483/123918206-ed4b2480-d983-11eb-8bc6-807386a09699.png)
![20210630090251](https://user-images.githubusercontent.com/5732483/123918212-ef14e800-d983-11eb-9b95-97ef28cf2e99.png)
![20210630090302](https://user-images.githubusercontent.com/5732483/123918219-f0deab80-d983-11eb-9a53-4fe094ded1a0.png)

https://user-images.githubusercontent.com/5732483/123918263-fd630400-d983-11eb-966e-99be3ca8676b.MP4

https://user-images.githubusercontent.com/5732483/123918289-048a1200-d984-11eb-95e5-33b36be0432c.MP4

https://user-images.githubusercontent.com/5732483/123918302-081d9900-d984-11eb-8977-bf07edba11cd.MP4

Is my diagnostic correct (I swapped bits when soldering) ? 
Have anybody encountered the same problem ?
Can I just modify a palette or something else to correct this in software ?

**Comment by IanSB** [comment]
That looks like you have the 4 bits of each colour rotated by 1
i.e

Atari R0 to Pi R1 
Atari R1 to Pi R2
Atari R2 to Pi R3 
Atari R3 to Pi R0
 
Same for the other colours I think

**Comment by pixelk0** [comment]
OK, thanks, I'll redo my soldering (and my photos for future installations)

**Comment by IanSB** [comment]
@pixelk0 
Note I have changed the above table as I think I got the rotation in the wrong direction

**Comment by pixelk0** [comment]
I mis-identified the pins on the STe's motherboard, and forgot that the bitness is reversed, here is the definitive pinout for the STe to the RGB2HDMI :

![STE_RGB_DAC-SYNC_v3](https://user-images.githubusercontent.com/5732483/124193866-e2011180-dac7-11eb-95ec-914855c7fa58.jpg)

This issue can be closed, thank you so much IanSB !

**Comment by luciust** [comment]
@pixelk0 @IanSB 
Thanks! I can confirm that it fixes my issues too from: https://github.com/IanSB/RGBtoHDMI/issues
