### ISSUE TITLE
NTSC artifacting or maybe palette for the CoCo 2 is a little off.

### ISSUE THREAD

**Issue by qbancoffee** [hoglet67/RGBtoHDMI#217]
I was testing Donut Dilemma on for the CoCo2 and I can't seem to get the colors to match up with what the game looks like on 
the online CoCo emulator.
https://www.6809.org.uk/xroar/online/ 

Here are some captures from the RGB to HDMI board compared to screen caps on my computer
![capture2](https://user-images.githubusercontent.com/5752734/124028126-a2e89880-d9c1-11eb-80da-c2bfd8c95292.png)
![Screenshot from 2021-06-30 16-19-48](https://user-images.githubusercontent.com/5752734/124028145-aa0fa680-d9c1-11eb-98e4-482ca2e82f0d.png)
![capture4](https://user-images.githubusercontent.com/5752734/124028212-bdbb0d00-d9c1-11eb-942e-560d8ee4fa72.png)
![Screenshot from 2021-06-30 16-21-01](https://user-images.githubusercontent.com/5752734/124028219-c0b5fd80-d9c1-11eb-8ba6-9ffa0f6db4ab.png)

**Comment by IanSB** [comment]
Those are actual colours, not artifact ones and the standard RGBtoHDMI palette generates them mathematically from the original YUV values in the 6847 datasheet so the XRoar values may have some artistic licence. However I also included a palette to match XRoar so go into the palette menu and change the palette to "Dragon CoCo Emulators" and see how that looks.

**Comment by qbancoffee** [comment]
I think your right about the artistic license, I've been looking at the authors website and although the images he has on display are for a coco 3, they are closer to what is being output by the pi.
https://nickmarentes.com/ProjectArchive/donutcc.html

**Comment by qbancoffee** [comment]
> However I also included a palette to match XRoar

Doesn't seem to match up with Xroar with any of the palettes but I'll take the screenshot and ask on the coco discord server.

**Comment by IanSB** [comment]
>Doesn't seem to match up with Xroar with any of the palettes but I'll take the screenshot and ask on the coco discord server.

I think the emulator palette values came from Xroar but it was a couple of years ago so they may have been changed in xroar since then

**Comment by qbancoffee** [comment]
Tomorrow I'll reconnect the RF can and hook it up to my tv to see if the colors are close.
Nick Marentes has some PAL images that match what I'm seeing.

https://nickmarentes.com/ProjectArchive/pipes.html

If you scroll down he explains how you'll only see this correctly on a PAL tv.

**Comment by IanSB** [comment]
>If you scroll down he explains how you'll only see this correctly on a PAL tv

He's using PAL artifacting which uses different colours on adjacent lines to get the PAL decoder to average to a new colour.
PAL artifacting isn't supported yet but there is a reserved option for that in one of the menus.
I think some Commodore 64 demos use that as well.

**Comment by qbancoffee** [comment]
I connected the rf can to my coco2 and loaded donut dilemma and except for the background pattern, it looks very similar but still a little off. Do you think this is close enough?

![20210701_165151](https://user-images.githubusercontent.com/5752734/124188941-f6c0b380-da8d-11eb-8d07-8da4c2779650.jpg)
![20210701_165219](https://user-images.githubusercontent.com/5752734/124188976-03dda280-da8e-11eb-999f-2eed024e0ea3.jpg)
![20210701_165137](https://user-images.githubusercontent.com/5752734/124188993-0b9d4700-da8e-11eb-95a9-8a46af86f8c8.jpg)

**Comment by qbancoffee** [comment]
> PAL artifacting isn't supported yet

Oh imissed that.

**Comment by IanSB** [comment]
Other than the red/blue artifacting I think my colours are a better match for the off screen, look at the orange donuts, they are almost red on Xroar.

That program isn'r really useful for testing the standard colours though. 
Are there any video test programs that run through all screens displaying all colours as that would be more useful.
In the meantime, an off screen photo of the NTSC RF output displaying the for/next loop colour blocks might be useful

**Comment by qbancoffee** [comment]
> Are there any video test programs that run through all screens displaying all colours as that would be more useful.

I've been looking around but I don't see one.



> I think my colours are a better match for the off screen

Yes, I should have said that your implementation is a better match.



> In the meantime, an off screen photo of the NTSC RF output displaying the for/next loop colour blocks might be useful

o.k. ill hook it up and check

**Comment by qbancoffee** [comment]
It look horrible but....

![20210701_212553_HDR](https://user-images.githubusercontent.com/5752734/124207283-2d5cf500-dab3-11eb-835c-8658e9a0f6ad.jpg)

**Comment by qbancoffee** [comment]
I can't really get a good picture of it with my phone. The yellow looks green in the picture but not on the screen

**Comment by qbancoffee** [comment]
![20210701_213429](https://user-images.githubusercontent.com/5752734/124208011-b163ac80-dab4-11eb-849d-ce92806b826a.jpg)

**Comment by IanSB** [comment]
The cyan looks very blue as well is that the same in person?

**Comment by IanSB** [comment]
Here's a PAL off screen:
![pal](https://user-images.githubusercontent.com/45300594/124208706-05d05180-dae0-11eb-9d06-f3eda3670072.jpg)

**Comment by qbancoffee** [comment]
> The cyan looks very blue as well is that the same in person?

It's pretty close in person. Here is a better picture and anything that is in the center of the pic is lighter than in person.
![DSC00082](https://user-images.githubusercontent.com/5752734/124210197-01dd0900-dab9-11eb-861a-8097f2e613f3.JPG)

**Comment by qbancoffee** [comment]
So a couple of days ago I saw a TV in a trash pile and I just drove over and trash picked it in the rain.....
To my delight and my wifes' dismay it works.

Here's a picture.

![20210701_230315_HDR](https://user-images.githubusercontent.com/5752734/124215052-4e2c4700-dac1-11eb-9d98-b19accddefee.jpg)

**Comment by qbancoffee** [comment]
This video better shows what the colors actually look like.
https://youtu.be/qtcAOyhdAxs

**Comment by IanSB** [comment]
I've tweaked the palette generation algorithm and it's now very close to the PAL output:
![capture17](https://user-images.githubusercontent.com/45300594/124299572-7cf3fd00-db55-11eb-9b80-0739d9e9d0a8.png)
![pal](https://user-images.githubusercontent.com/45300594/124208706-05d05180-dae0-11eb-9d06-f3eda3670072.jpg)

The NTSC output is a bit indeterminate as it is affected by phase shifts. You might be able to get it to match the PAL output by adjusting the tint control on the TV.

**Comment by qbancoffee** [comment]
> You might be able to get it to match the PAL output by adjusting the tint control on the TV.

Yes, and although not all sets were made the same, I made sure to set the color/tint to default before testing.
I have a broken coco composite board that I'll try and repair to see if I can get better results.

**Comment by IanSB** [comment]
You can also adjust the tint setting in the palette menu to get the palette to match the tv.

**Comment by qbancoffee** [comment]
I posted this under the wrong issue earlier

Here are two videos where I compare the colors on my dell monitor and my television set.

https://youtu.be/wPlHFHk4y48
https://youtu.be/dPttAgc3Bog

I also noticed that the aspect ratio isn't quite 4:3, it seems longer on horizontal.(I measured it and it's 240mm X 318 mm so it is 4:3)

As far as the palette goes, I could sit in from of my television set and come up with numbers
that are closer to what I am seeing. If you want me to, where in the code should I look?

**Comment by qbancoffee** [comment]
I posted the links to the videos I made on CoCo Discord and asked to see which is closer to what it should look like.
I guess the consensus is that the old TV is closest. Here is are some of the responses.

_"Except for the white comparison (white isn't actually supposed to be white, it's "buff"), your observations seem pretty right."_

_" Looking at your two videos above. The Yellow, Blue and the Red (CLS3 and CLS4) are definitely a little off from what "normal" TV's did back in the day (the yellow might be acceptable; while it's an orangish yellow, it is still a yellow compared to the regular orange (CLS8). Your NTSC TV looks exactly as I remember it being on older TV's."_

_"For the orange text character set - the colors should be really dark red (darker than CLS 4) on a yellowish/orange background (which is not the same as regular yellow (CLS2) or regular orange (CLS8). To see the dark red more clearly, you can do this from the OK prompt: POKE 359,57:POKE 65314,8. Then hit SHIFT-0 for lowercase and type a couple lines of text."_

**Comment by IanSB** [comment]
>If you want me to, where in the code should I look?

The relevant code is is osd.c, look for:
case PALETTE_ATOM_MKI_FULL:
(The name dates back to before dragon/coco support etc)
However it is generated algorithmically from the YUV voltage values but doesn't take into account other things like gamma correction.

What you could try is to adjust the tint and contrast settings in the palette menu for each colour individually ignoring the others and post the list of those settings that make each colour match the TV.
i.e. concentrate on RED, and adjust tint and contrast until RED looks closest to the TV (ignoring the other colours)
Then repeat for each colour in turn so you end up with a list of those settings for each colour.
I'll apply those adjustment values to the palette for each colour and the resulting palette should then match the TV

**Comment by qbancoffee** [comment]
> What you could try is to adjust the tint and contrast settings in the palette menu for each colour individually ignoring the others and post the list of those settings that make each colour match the TV.

o.k. will do.

**Comment by qbancoffee** [comment]
o.k. , that was very hard.....
I could match the colors exactly by varying just the contrast and tint but they did improve.

Using the CoCo-emu palette, these are the colors that needed changing followed by the contrast and tint

| # | Color | Contrast | Tint |
| --------------- | --------------- | --------------- | --------------- |
| 2 | yellow | 89 | -33 |
| 3 | blue | 149 | 20 |
| 4 | red | 124 | -6 |
| 6 | cyan | 88 | -54 |

**Comment by qbancoffee** [comment]
Would it help If I gave you RGB values that you could use to apply corrections?

**Comment by IanSB** [comment]
@qbancoffee 
>Would it help If I gave you RGB values that you could use to apply corrections?

OK, I was trying to keep it algorithmically but I'll try using an RGB override on some colours

**Comment by IanSB** [comment]
@qbancoffee 

What is the best default for the NTSC phase? (0 or 180)
(I suppose it depends on how many games use each one as their default)

**Comment by qbancoffee** [comment]
o.k.
 I asked my wife to help me out because she is much better at matching colors than I am.
We used Kolour paint to match the colors visually and then I just copied the the values.
You don't need Hue and saturation but they were there so I added them here.
Also, I think the green already looks good.


| CLS# | Color | R | G | B | Hue | Saturation |
| ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- |
|1|green||||||
|2|yellow|216|254|0|69|100|
|3|blue|1|74|253|223|100|
|4|red|254|0|0|0|100|
|5|buff|205|210|224|224|8|
|6|cyan|57|180|216|194|74|
|7|magenta|241|67|194|316|72|
|8|orange|248|105|19|22|92|

**Comment by qbancoffee** [comment]
> What is the best default for the NTSC phase? (0 or 180)

So far 0 matches the games I'm using.
