### ISSUE TITLE
Analog Board: D1

### ISSUE THREAD

**Issue by jczmok-iag** [hoglet67/RGBtoHDMI#220]
Hi,

can somebody outline me how D1 needs to be soldered on the PCB ? There is no indication on the PCB on how to mount the Shottky Diode,e.g. orientation

**Comment by IanSB** [comment]
The banded end of the diode goes to the end marked with [ (the top and bottom lines are much longer on the board)
The diode is only required if you are going to inject +5v via the 6 way connector instead of powering the board using a 5v USB power supply plugged into the Pi zero

**Comment by jczmok-iag** [comment]
clear, but just for completeness, the marked diode would be this way D1 |== R7 or D1 ==| R7 ?
