### ISSUE TITLE
Wiring for various machines?

### ISSUE THREAD

**Issue by earlthesquirrel** [hoglet67/RGBtoHDMI#228]
I see mention for Commodore 64, CoCo, etc.

I'm wondering, is there any documentation on how to wire up these various machine?

**Comment by hoglet67** [comment]
There already is:
https://github.com/hoglet67/RGBtoHDMI/wiki/Cables

**Comment by earlthesquirrel** [comment]
Thanks!  I had been reading the various docs and hadn't come across that
yet...
Not sure why...

Got my unit this past week, and am anxious to test it out on various
machines!

Thanks.

Earl
