### ISSUE TITLE
Is it possible to use Raspberry Pi 3 or 4 instead of Pi Zero? 

### ISSUE THREAD

**Issue by alex3331** [hoglet67/RGBtoHDMI#237]
I got a couple of 9572 in 44 pin PLCC and designed a hat using this larger part, so my hat is larger than the one with SMT components, so I fit it in Pi 3  hat dimensions.  Is it possible to plug it into Pi 3 or Pi 4?

**Comment by hoglet67** [comment]
Sorry, all bets are off with anything other than a Pi Zero.

The build system does spit out kernels for each of the Pi architectures, but we only do testing regular on the Pi Zero, and there are many known issues with the Pi 3A+ and Pi 4. Generally their memory system has longer / more variable latency, which is detrimental to this application.

See #135 for the kind of problem we hit.
