### ISSUE TITLE
Amiga pink sparklies on black/grey transition

### ISSUE THREAD

**Issue by psoma** [hoglet67/RGBtoHDMI#241]
- Multiple builds (including latest)
- Capacitor fitted
- Numerous timing/overclocking settings tweaked without any change
- Tried multiple cards and multiple Amigas
- Tried on both Amiga 500 and Amiga 2000
- ... getting the same result
- Specifically on hard transition from black to grey

[YouTube Link to video example](https://www.youtube.com/watch?v=gAjQK-vwkJM)

Can consistently reproduce it in the first screen of Police Quest here as a very clear example.

**Comment by Bloodmosher** [comment]
Which board styles and revision numbers specifically?

**Comment by psoma** [comment]
Closed - moved to c0pperdragon's Amiga RGBtoHDMI github

**Comment by dendrown** [comment]
@psoma : could you please post a link to this issue on c0pperdragon's github repo?  I am having the same problem, and I cannot find an issue/discussion with [c0pperdragon](https://github.com/c0pperdragon/RGBtoHDMI).

At least I think it may be the same problem.  Your youtube link no longer exists.

Thanks!
