### ISSUE TITLE
Raspberry Pi Zero 2!!!

### ISSUE THREAD

**Issue by Croccy22** [hoglet67/RGBtoHDMI#243]
https://thepihut.com/products/raspberry-pi-zero-2

So now the lack of Pi zeros everywhere makes sense. I didn't know this was coming.

I have ordered one so will test when I get it, but with RGBtoHDMI being a bare metal project, do you think the current code will work or will it need to be re-written/re-compiled?

**Comment by solarmon** [comment]
Hi,

I appreciate this ticket has been closed, but what is the status of whether the Pi Zero W v2 will be supported or not?

If the original Pi Zero 1.3 and Pi Zero WH will be end-of-life then there will no be a suitable alternative?

**Comment by abrugsch** [comment]
They are not EOL for a while yet. Just unavailable

**Comment by solarmon** [comment]
Just found https://www.raspberrypi.com/news/new-raspberry-pi-zero-2-w-2/ which states:

```
Are you discontinuing Zero and Zero W?
No. We seldom discontinue products, even where they have been superseded by more modern product at the same price point. Zero 2 W is $5 more expensive than Zero W, and joins the Zero family as a third member.

Note that Zero and Zero W are currently experiencing supply constraints in the context of the global semiconductor shortage. We hope that this will be resolved in 2022.
```

Also, a response from a contact from the Raspberry Pi Foundation states that:

"Raspberry Pi Zero and Raspberry Pi Zero W will remain in production until at least January 2026."
