### ISSUE TITLE
quad core pi zero

### ISSUE THREAD

**Issue by rogerjowett** [hoglet67/RGBtoHDMI#245]
https://www.tomshardware.com/uk/news/radxa-zero-sbc-pi-zero-clone

this is a quad core pi zero
raspberry pi is also making quad core pi zero
please would it be possible to use this in an rgb2hdmi interface and simultaneously encode the video output to mpeg2 avi video file? 
rogerjowett@gmail.com
Please let me know what you think

**Comment by hoglet67** [comment]
Sorry, this won't be possible.

**Comment by hoglet67** [comment]
Encoding MPEG2 video is currently out of scope for this project.

**Comment by rogerjowett** [comment]
do you know absolutely anyone for whom it might be in scope please?

**Comment by hoglet67** [comment]
Roger, please stop spamming this project with off-topic question, otherwise I will be forced to block you.

**Comment by hoglet67** [comment]
Seems you have a bit of a reputation for spamming!
https://www.cpcwiki.eu/forum/general-discussion/who-is-roger-jowett/
