### ISSUE TITLE
are you sure?

### ISSUE THREAD

**Issue by rogerjowett** [hoglet67/RGBtoHDMI#246]
100% certain?

https://www.tomshardware.com/uk/news/radxa-zero-sbc-pi-zero-clone

this is a 100mhz 6502 could it encode mpeg2 video output please?

**Comment by hoglet67** [comment]
Encoding MPEG2 video is currently out of scope for this project.

**Comment by rogerjowett** [comment]
would you know absolutely anyone for whom it might be in scope please?
