### ISSUE TITLE
Atari 2600 support?

### ISSUE THREAD

**Issue by DFL1973** [hoglet67/RGBtoHDMI#261]
Can an NTSC Atari 2600 profile be included in some future release?

**Comment by IanSB** [comment]
The Atari 2600 has the colour info already encoded onto a subcarrier in the TIA so a simple pickup of the baseband video isn't possible. It might be possible to scale the output if you have an RGB analog mod fitted but I've not tried that.

**Comment by DFL1973** [comment]
I see, thanks for the info. I will look for some kind of RGB mod.
