### ISSUE TITLE
R1 on analog board BOM wiki page has incorrect value.

### ISSUE THREAD

**Issue by antongale** [hoglet67/RGBtoHDMI#263]
Part Ref: R1 on the Wiki states 470 Ohms, the value on the schematic reads 100 Ohms.

**Comment by IanSB** [comment]
The wiki (470 Ohms) is correct, I changed it but I never got around to updating the schematic. Some of the part numbers have changed as well.

**Comment by antongale** [comment]
Thank you for the clarification.  I searched for pictures of other builds around the Internet and saw a couple with 100 Ohms so assumed the BOM was in error.  I will switch my builds to 470 Ohms.  Thank you again.

**Comment by IanSB** [comment]
I've just updated the schematic so it will get updated in the next stable release
