### ISSUE TITLE
Atari MegaSTE  60mhz NA machine 

### ISSUE THREAD

**Issue by Biker1bob** [hoglet67/RGBtoHDMI#268]
I have built one of the devices up with a 12bit board I purchased assembled - its an IanSB board.

This is the topic thread I am getting my info from https://www.atari-forum.com/viewtopic.php?t=40201

My situation is - in LOW or MEDIUM resolution - where I would use the RGB colour (AKA NOT MONO)  Green is substituted for Black - I cannot get the device to produce a BLACK - It is using the STE 50hz profile. My monitor is able to do 50hz. EVERYTHING else looks fine except where a black should be there is Green. 

I have adjust every setting in the software I can think of. I have rechecked all my wiring 10+ times.. I am at a loss. Any suggestions would be appreciated
![20220124_162536](https://user-images.githubusercontent.com/33105915/151193879-361e5905-2077-4feb-8ce5-af777ee7b224.jpg)
![20220122_152203](https://user-images.githubusercontent.com/33105915/151193908-ed80cba2-2a94-499a-9b5c-726c7139f4d4.jpg)
![20220122_152133](https://user-images.githubusercontent.com/33105915/151193918-8d4487ad-11d1-4d01-acc8-dec88f7db288.jpg)

**Comment by IanSB** [comment]
It seems likely that one of the four green bits is stuck high.
Based on the brightness of the green it looks like the highest bit G3 is stuck on so maybe check your soldering around that signal or try disconnecting it entirely.
Are some other colours a bit 'off colour'? (White would still be white but colours would have some green added to them)

I don't have an STE but is there any video test program that displays the full colour test patterns for that machine.
I have a program like that for the Amiga which makes it easy to work out which bit is the problem. It produces an output like this:
![capture0](https://user-images.githubusercontent.com/45300594/151264359-419feb85-bbc4-4804-9f9a-e1879a710129.png)

Which shows the full 16 levels of red, green & blue and that makes it easy to confirm which bit is stuck.

Even if you can't find a program, if you post a screencap (Short press of SW2 - file on the SD card) as I can look at the RGB level of the black background with a paint program.

**Comment by Biker1bob** [comment]
There is the colour test that the Diagnostic cartridge shows. I have tried removing the connections.. not sure that I did it one at a time.. aka just G3.. I will do a screen shot of the Diagnostic screen and post. Thanks for the response.

**Comment by Biker1bob** [comment]
Ok, so I did some screen captures.. I also undid all the connections.. re-examined all the solder joints.. everything is good. There is another interesting development. - when the HDMI device is wired up and powered.. it does modify the output of the Monitor port. see the attached pics for the colour bars and the changes when output to Monitor power <> VGA on monitor.
![capture0](https://user-images.githubusercontent.com/33105915/151435346-e1baa8b9-360b-47d5-8212-feb62eef2d1b.png)
![capture1](https://user-images.githubusercontent.com/33105915/151435361-db651a8b-ffc9-4df2-96ce-3ab613df47ed.png)
![capture2](https://user-images.githubusercontent.com/33105915/151435368-2ca1f4ea-f6e4-4bde-b5b5-737bc891d256.png)
![vga1](https://user-images.githubusercontent.com/33105915/151435410-230444d8-4cee-4326-b8d6-08edb051a58e.jpg)
![vga2](https://user-images.githubusercontent.com/33105915/151435422-fd0d2f5b-aafc-4977-84f2-e8cb6f601b4d.jpg)

**Comment by IanSB** [comment]
@Biker1bob 
>it should not effect the output correct?

Correct. 
The green value in the above PNGs is 68 which implies that it is G2, not G3 that's the problem. (it would be double that for G3, half for G1 and a quarter for G0)

So repeat the disconnection test with G2.

How are you picking up the signals? directly from the chip pins or via the resistors that are connected to those pins. (if the latter, make sure you are on the right end of the resistors which might not always be the same on all resistors)  

If the pickup points are OK then it is possible that the G2 signal is shorted to a logic high somewhere in the converter

First disconnect the converter from the Atari (unplug the 16 way cable) and try powering it with a USB power supply (USB connector nearest the 16 way connector)
If you get a green screen then it means G2 is shorted to a logic high signal on one of the boards or possibly a faulty CPLD.

If you get a black screen then it's more likely that G2 is shorted to another input signal like the HSYNC or VSYNC inputs
The Hsync input has composite sync which is normally high during video (this is less likely as it would affect the sync)
The Vsync input normally has the MONO signal and I think the MONO signal is high when the RGB signal is in use.
(you can check that by disconnecting both G2 and MONO from the STE)
Check the CPLD board and extender board separately for any solder bridges or use a multimeter if you have one

Don't forget to unplug the USB power supply before reconnecting to the computer.

**Comment by Biker1bob** [comment]
> Correct. The green value in the above PNGs is 68 which implies that it is G2, not G3 that's the problem. (it would be double that for G3, half for G1 and a quarter for G0)
> 
> So repeat the disconnection test with G2. If the output stays green but the monitor port looks normal that would confirm an issue with the converter and you shouldn't reconnect G2 until that is sorted.
> 
Just did this.. NOTHING changed. G2 did not affect anything on the HDMI OUT OR the Monitor out. 


> How are you picking up the signals? directly from the chip pins or via the resistors that are connected to those pins. (if the latter, make sure you are on the right end of the resistors which might not always be the same on all resistors)
> 
> If the pickup points are OK then it is possible that the G2 signal is shorted to a logic high somewhere in the converter

Yes from the legs of the resistors just after the chip - aka before the resisted values. Several others have done in just this place so I am very sure I am correct.
 
> First disconnect the converter from the Atari (unplug the 16 way cable) and try powering it with a USB power supply (USB connector nearest the 16 way connector) If you get a green screen then it means G2 is shorted to a logic high signal on one of the boards or possibly a faulty CPLD.
> 
> If you get a black screen then it's more likely that G2 is shorted to another input signal like the HSYNC or VSYNC inputs The Hsync input has composite sync which is normally high during video (this is less likely as it would affect the sync) The Vsync input normally has the MONO signal and I think the MONO signal is high when the RGB signal is in use. (you can check that by disconnecting both G2 and MONO from the STE) Check the CPLD board and extender board separately for any solder bridges or use a multimeter if you have one

OK, so we have a green screen with just external USB power.. so I will start checking my soldering again.. and check for shorts with the multimeter

![capture8](https://user-images.githubusercontent.com/33105915/151585302-7b685fc0-829a-4edd-b73f-b0d0d578f577.png)

**Comment by Biker1bob** [comment]
Think I found it.. On the clpd - it also had continuity with G2
![joint](https://user-images.githubusercontent.com/33105915/151587309-6087b844-11cd-47a9-b7bd-1d4cdf4953df.jpg)
.

**Comment by IanSB** [comment]
>Think I found it.. On the clpd - it also had continuity with G2

Yes, that's almost certainly it, that's pins 35 & 36 which are +3.3V and G2 respectively

**Comment by Biker1bob** [comment]
YES, that was it IanSB - BLACK screen now. Thankyou so much for pointing out the G2 issue.. it allowed me to follow your steps and start investigating with the multimeter knowing a start point! :)
