### ISSUE TITLE
Incorrect ZX Spectrum 128/+2 palette

### ISSUE THREAD

**Issue by shinedeveloper** [hoglet67/RGBtoHDMI#269]
I tried the ZX Spectrum 128/+2 (grey) profile and found that the palette is incorrectly set to:
palette=RGBrgb_(Spectrum)
whereas it should be:
palette=RGBI_(Spectrum)

It manifests itself in the way that the bright colors are weird. Bright black, for instance, is greenish. When corrected, it works fine.

I believe that the ZX Spectrum +2A/+2B/+3 profile is also set the other way round. I don't have the analog extension board so I cannot test it, but it's set to:
palette=RGBI_(Spectrum)
whereas I believe it should be:
palette=RGBrgb_(Spectrum)

**Comment by IanSB** [comment]
You are correct, not sure how that happened but it will be fixed on the next beta due soon.

**Comment by shinedeveloper** [comment]
Great, thank you.

**Comment by IanSB** [comment]
This is fixed in Beta53
https://github.com/IanSB/RGBtoHDMI/releases
