### ISSUE TITLE
Feature Request: Soft reset button on GPIO header

### ISSUE THREAD

**Issue by texelec** [hoglet67/RGBtoHDMI#274]
It's getting hard to get Raspberry Pi Zeros lately, and the newer 2W and the Banana Pi do not have the pins for a HW reset button any longer.  Is there a way to add a feature for a soft reset in the bare metal code and tie it to an unused pin?  Theat would be a handy ability.  Thanks!

**Comment by IanSB** [comment]
A soft reset button would be technically possible but the main problem is that there aren't any spare GPIOs.
 
However you can still add the reset functionality on the zero2W (or any other Pi model) as detailed here:
https://github.com/hoglet67/RGBtoHDMI/wiki/Bill-of-Materials-%28Pi-Zero%29
