### ISSUE TITLE
Mastersystem / MegaDrive / Gensis RGBtoHDMI

### ISSUE THREAD

**Issue by ryanm101** [hoglet67/RGBtoHDMI#285]
According to: https://segaretro.org/Sega_Mega_Drive/Technical_specifications & https://segaretro.org/Sega_Mega_Drive/Palettes_and_CRAM its 9bit RGB (3bits per colour)

https://console5.com/techwiki/images//8/8b/Mega_Drive_1_-_VA3_-_Audio%2C_Video_%28Sheet_2%29.png shows the pins from the IC. Might need an ADC to convert 1st?

Master System
https://segaretro.org/Sega_Master_System/Technical_specifications & https://segaretro.org/Palette#Master_System_palette
https://console5.com/techwiki/images/0/0e/SMS_Schematic_-_IC_BOARD_PB_PAL_VA1_-_171-5534_-_1_of_2.png
https://console5.com/techwiki/images/5/59/SMS_Schematic_-_IC_BOARD_PB_PAL_VA1_-_171-5534_-_2_of_2.png

**Comment by IanSB** [comment]
Although it has a low enough number of levels (9 bits per pixel) the output from the chip is already in analog. The existing analog board can only cope with 4 levels each for RGB and you would need an A to D that could accurately extract the 8 levels each from the RGB signals.

**Comment by ryanm101** [comment]
Would ADV7401 do the trick?

**Comment by ryanm101** [comment]
I've found and ordered a TVP7002 in the hope that will do the job

**Comment by davedoc1984** [comment]
What about the Audio though?

**Comment by c0pperdragon** [comment]
The Sega Master System has a simple 6-bit palette with 2 bits per R,G,B channel. So 4 levels each, which should be possible with the analog board and mounted extra comparator. Pixel clock is also quite moderate.
(I just looked into this to make sure that there is no need to come up with a Lumacode adapter ;-) )
