### ISSUE TITLE
Amiga 500 -colors are displayed incorrectly | black is dark red

### ISSUE THREAD

**Issue by sascha70** [hoglet67/RGBtoHDMI#292]
Hello community,

unfortunately a bug is driving me crazy with the Amiga 500. 

Unfortunately, the colors are displayed somewhat incorrectly for me. What should be black is dark red. I used the Beta54 version from JanBeta and the version from main tree 20211224_c97f06a release. All have the same problem. The adapter is from LinuxJedi (https://github.com/LinuxJedi/AmigaRGBtoHDMI/tree/main/Amiga500CPLD).

Do you have a solution?

Thanks

sasch
![capture8](https://user-images.githubusercontent.com/106908158/172044306-4f77b9d2-e44d-43ce-a68f-d98379d784e6.png)
a

**Comment by abrugsch** [comment]
Who built it as that looks like one of the data lines isn't soldered
correctly on the CPLD. It might just need a re-flow. I doubt it's a
firmware bug as when I've built these, a slight colour shift usually means
one pin hasn't made a proper joint.

**Comment by sascha70** [comment]
Thank you for your tip. It is indeed the connector of the Pi Zero! 

With a Pi 3 A+ it works wonderfully.

Greetings

Sascha
