### ISSUE TITLE
Raspberry PI Zero V1.2

### ISSUE THREAD

**Issue by jarek090** [hoglet67/RGBtoHDMI#297]
Hello ,
I have raspberry PI Zero V1.2 (2015 year). Any chance to run on it ? Right now I have black screen and it seems it is not loading. ACT diode not blinking.
Thank you!
Jarek

EDIT:
It works...
For someone who is facing issue:

Raspberry Pi Zero Ver 1.2 (2015) works fine.

I had HDMI connected to amplituner which does not support 50Hz refresh rate. 
Connecting directly to monitor or setting 60Hz output in OSD config menu solves issue.

Thank you for real good nice project ! Image is saturated and sharp !

**Comment by abrugsch** [comment]
That's the exact one that's perfect for RGBtoHDMI.
Have you checked:
* That it works with a regular Pi OS Sdcard
* That it is connected to the the interface board properly
* That there are no soldering issues on the interface board (where did you
get it/did you build it yourself/what computer is it for?)

Soldering issues in particular cause the stated problem as if the pi
doesn't see a valid sync signal, it won't initiate the boot sequence and
appear 'dead'
