### ISSUE TITLE
12-Bit Extender on Rev. 3 CPLD board

### ISSUE THREAD

**Issue by c0pperdragon** [hoglet67/RGBtoHDMI#305]
I want to use my Issue 3 CPLD board to create an external upscaler for the Amiga. The obivious solution would be to use the 12-Bit extender board that would fit to an Issue 4 CPLD board.  As I don't have this board, I would just add the missing pin-socket to my Issue 3 board and wire up 4.7K resistors from the signals to GND.
The necessary holes for the headers seem to be already available on my board, even if they seem to have served a different purpose (JTAG programming) then.

So the question is of course,: Would there be any issue with this? 
I would just fit a 5 pin socket to the holes (4 signals, 1 GND), an use 4 SMD resistors and some wire for the termination. 
The extender board itself, I would try to simply etch myself.

**Comment by IanSB** [comment]
@c0pperdragon 

As you noticed, the issue 3 board doesn't support the 12 bit board and the extra holes on that board are for an external JTAG reprogramming header which was removed on the issue 4 board to add support for the 12 bit extender board but it would be technically possible to modify the issue 3 board.

You would have to cut the tracks to pins 3-6 of the JTAG header to free up those holes and fit a 4 way socket.  Then cut the existing tracks to pins 18, 21, 40 & 42 of the CPLD (B0, R0, G1, G0).  Finally wire those CPLD pins to the appropriate pins on the JTAG header.  (Some of the connections to the CPLD pins were used by earlier firmware but are not used by later firmware so the tracks can be cut and the signals re-allocated.) 

You can wire the 12 bit pickup directly to the Amiga but it would be preferable to use the external Amiga pickup board which is here:
http://github.com/hoglet67/RGBtoHDMI/tree/master/Kicad_Amiga_12Bit_Buffered_Pickup/V1

You can actually fit both your internal board and the external pickup board at the same time (which I do for software testing):
![both](https://user-images.githubusercontent.com/45300594/208552411-6963a950-9c13-4f35-a1b0-48325167efab.jpg)
