### ISSUE TITLE
Scanline level not configurable

### ISSUE THREAD

**Issue by wmoindrot** [hoglet67/RGBtoHDMI#326]
I'm running 20230517_eb620884 Release with my Amstrad PC1640 and the 'HEGA Auto' profile. I can turn on scanlines but I can't seem to alter the scanline level number from 0. I might have missed something, any ideas? Thanks, Will

**Comment by IanSB** [comment]
Multi level scanlines requires a double height frame buffer so try changing the FB Size in geometry to Double Height.
(Use save configuration to save any changes before exiting the menu)
You might have to repeat this for any sub-profile that has it set to off
