### ISSUE TITLE
OSD issue with 4bpp FB and  Six bits=On 

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#33]
If Six bits = On and FB Bits/pixel = 4 then the palette is slightly messed up when the OSD comes up. This is because capture_line_sixbits_4bpp captures 4 bit pixels.

**Comment by IanSB** [comment]
This was fixed in https://github.com/hoglet67/RGBtoHDMI/commit/76f56927423a935fffdec34f0b7fb29634357cb1

**Comment by hoglet67** [comment]
Thanks for fixing this.
