### ISSUE TITLE
Question on shifter for Atari Mega ST

### ISSUE THREAD

**Issue by timmcross** [hoglet67/RGBtoHDMI#352]
I built Atari ST pickup boards for the 1040 and 520 but recently picked up a Mega ST/2.  The shifter chip in there is a c070713-002.  Am I wrong that these shifters are different and incompatible with the pickup boards?

**Comment by IanSB** [comment]
@timmcross 

Yes they are different to the 40 pin shifters in the earlier computers.
You can solder the 12 bit extender wires directly to the shifter pins on such systems (or via buffer chips) and some people have done that. Note these shifters output 12bpp rather than 9bpp on the original systems.
