### ISSUE TITLE
Changing H Offset messes up Mode 7 alignment

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#37]

**Comment by IanSB** [comment]
This is expected behaviour as mode 7 needs alignment to modulo 12 pixels so it will phase in and out every 3 adjustments of H Offset. It could be fixed by adding / subtracting 4 for each adjustment of H-offset.

**Comment by hoglet67** [comment]
Maybe this should just be documented in a known issues file?

**Comment by hoglet67** [comment]
Closing as wontfix, as this is expected behaviour.
