### ISSUE TITLE
Output from MDA original card not showing first three columns!

### ISSUE THREAD

**Issue by gfmoore** [hoglet67/RGBtoHDMI#371]
Hi, thanks for your work on this. 

I am using it to output to a old VGA display (but have tried also on a HDMI display) and with it set to MDA I get the output as I expect, but it is missing the first three columns as shown in the image. I have no ideas how to adjust this and can find no references on a web search. Chat GPT of no use either ;) 

![IMG_20240318_163317 1](https://github.com/hoglet67/RGBtoHDMI/assets/22768967/b14732d2-f35a-4d30-84e9-674a18257aba)

Thanks for any help/advice.

**Comment by IanSB** [comment]
@gfmoore 
Try adjusting the H offset value in the Geometry menu.
Use Save Configuration to save any changes.

**Comment by gfmoore** [comment]
Brilliant, set it back to zero and all very good, many thanks.

**Comment by IanSB** [comment]
@gfmoore 
Are you using a genuine original IBM MDA?
If so then perhaps that should be the default setting (I don't have one myself so I have to rely on user submitted profiles which sometimes are not setup entirely correctly).
Also there is another adjustment in the Sampling Menu:  "Pixel H Offset" which can be used to fine tune the offset to pixel accuracy.
(You need to check both the right and left hand edges of the screen to ensure that video is not missing a pixel)

**Comment by gfmoore** [comment]
Yes it's a genuine MDA card (version 2) I think, without the headers for the light pen. I set the offset to zero and it seems good. I'll check the right side tomorrow, but I think it's ok.

Regards,
Gordon Moore
***@***.***
________________________________
