### ISSUE TITLE
Pi Zero 2 support?

### ISSUE THREAD

**Issue by angelsix** [hoglet67/RGBtoHDMI#375]
I'm just using your awesome project on a C64. I have used the RGBtoHDMI for Amiga fork before for the Amiga stuff and that works with the Pi Zero 2.

However, I noticed using this branch for the C64 project, it doesn't work with Pi Zero 2 boards. Any support for them coming or should it already work? 

The same Pi 2 boards worth with Amiga builds using the same SD card so it isn't an SD card issue, or HDMI etc... and using a Pi Zero 1 works fine.

**Comment by IanSB** [comment]
@angelsix 
>However, I noticed using this branch for the C64 project, it doesn't work with Pi Zero 2 boards. Any support for them coming or should it already work?

It should already work. Support for the zero 2 was added not long after it was launched and I'm regularly testing on several zero 2 setups. It should also work with any other raspberry Pi 1, 2 3 or 4 although only the Pi 4 is useful as that can output integer scaling at 4k/60Hz whereas the zeros are limited to 4k/30Hz.  The Pi 5 is not yet supported.

What problem are you seeing?

**Comment by angelsix** [comment]
Absolutely nothing happens. No LEDs no boot, nothing from HDMI. Put that same SD into a Pi 1 and all works. Tried on 5 lots of Pi 2 that all work with Amiga branch to confirm both SD, Pi and HDMI are all ok

**Comment by IanSB** [comment]
@angelsix 

If you are using the latest release, try unplugging the CPLD board from the zero2 and just insert the SD card, power and HDMI cable.
You should get a HDMI output displaying the main menu with the error "CPLD Not Fitted" at the top. This would confirm that the zero2 is booting from the SD card OK.

What "Amiga branch" are you using? It should run on the same software.

**Comment by IanSB** [comment]
@angelsix 

One other possibility occurred to me if your SD cards aren't even booting using the above "CPLD not fitted" suggestion:
I recall seeing a problem with some Pi1 models that wouldn't boot with some SD cards that would otherwise boot on other models and it was some issue with the SD card format. After reformatting them using the official SD Association formatter rather than windows formatter they booted OK so give that a try.
Also make sure the cards are 32GB or less as there will be issues with fat64 formatting on cards greater than 32GB 
https://www.sdcard.org/downloads/formatter/

**Comment by angelsix** [comment]
Nothing with or without CPLD. I'll try formatting using that tool

**Comment by angelsix** [comment]
For the Amiga branch that works, I mean this https://github.com/michalsc/Emu68/releases/ when its used in an Amiga. This SD card works fine on Pi Zero 2, but this branch does not. I'll let you know if the SD card format works

**Comment by IanSB** [comment]
@angelsix 
>Nothing with or without CPLD. I'll try formatting using that tool

Then it seems likely that the Pi isn't even loading its firmware so if reformatting doesn't help, maybe there has been a revision of the zero 2 silicon that requires the latest firmware files as the ones in the release are quite old.
Try replacing the firmware files in the root of the SD card with the latest:
[Pi_firmware.zip](https://github.com/hoglet67/RGBtoHDMI/files/15107418/Pi_firmware.zip)

**Comment by angelsix** [comment]
Just another brand of SD worked this time. So must be a specific SD card it doesn't like

**Comment by IanSB** [comment]
@angelsix 

For the benefit of anyone else that may have this problem, what was the brand and size of the problem SD cards?
Also had you tried reformatting them as suggested above?

**Comment by angelsix** [comment]
SanDisk Ultra. But I suspect they are fake as they are the most common ones to have fake prints over them. Working one was Lexar 32GB
