### ISSUE TITLE
Custom boards for various RGB outputs

### ISSUE THREAD

**Issue by angelsix** [hoglet67/RGBtoHDMI#384]
I would love to start making custom projects for many consoles. Is there anywhere I can read up on the general process required to get RGB from various consoles into the RGB2HDMI boards to work?

For example, Master System. It outputs native RGB already. Perfect starting point to integrate.

**Comment by c0pperdragon** [comment]
From theoretical considerations, the RGBtoHDMI with added Analog board sould be able to do this. Making a suitable profile and palette file is probably a bit involved. The project wiki should contain most of what is needed here.

**Comment by angelsix** [comment]
Ok thanks, I'll try and delve in when I can to add some custom support. I'll take a look at the wiki
