### ISSUE TITLE
RGBtoHDMI Mono & LumaCode

### ISSUE THREAD

**Issue by wiesl** [hoglet67/RGBtoHDMI#390]
Can you please upload the RGBtoHDMI Mono & LumaCode schematic & PCB to the git repo.

RGBtoHDMI Mono & LumaCode
https://www.tindie.com/products/c0pperdragon/rgbtohdmi-mono-lumacode/

Thnx.

**Comment by wiesl** [comment]
Found documentation at: https://github.com/c0pperdragon/LumaCode/wiki/Overview

**Comment by IanSB** [comment]
@wiesl 

The Mono & LumaCode board is only available assembled. To get equivalent functionality, use the standard CPLD board plus analog board but with only the sync and green inputs connected. (As mentioned on the above link, connect lumacode video to pins 2 & 4 on the analog input connector and ground to pin 1).
