### ISSUE TITLE
V3: Change short sync default back to 6.144us and make configurable

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#41]
See this post for why:
https://stardot.org.uk/forums/viewtopic.php?p=230515#p230515

Effectively reverting this commit: f369754c

Dave

**Comment by IanSB** [comment]
Could this be switched by the existing m7disable setting as it seems to be mode7 / bbc specific?

**Comment by hoglet67** [comment]
Yes, it probably could.

Or if you add the concept of machines, it could be keyed off that.

On another subject, I've started working on screen capture. I've pushed some stuff, but it's not working reliably yet. I'm occasionally seeing SD Card errors (CMD25). And the end of the file is corrupt. I'm also going to switch PNG library tomorrow.

**Comment by hoglet67** [comment]
Ian addressed this in 41027864
