### ISSUE TITLE
Screen Capture: Option to include OSD (for documentation purposes)

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#48]
Not sure how this would work though...

How would a capture be initiated? All buttons are in use for menu navigation.

Possibly we could use the link (and spare gpio) as a 4th switch.

**Comment by IanSB** [comment]
This could be done by pressing both the cursor up and down buttons simultaneously as that would only result in the pointer moving up or down in a menu if one key was detected before the other

**Comment by hoglet67** [comment]
This is now done.
