### ISSUE TITLE
Unconnected RGB inputs

### ISSUE THREAD

**Issue by IanSB** [hoglet67/RGBtoHDMI#55]
Are any unconnected RGB inputs floating or do they have internal weak pullups/downs?

**Comment by hoglet67** [comment]
The CPLD does not have any internal pullups/pulldowns. However, the 74LS08 TTL inputs will act like a 22K (ish) pullup, so if you disconnect one of the R/G/B inputs then it is seen as high.

On the next revision of the RGBtoHDMI hat I had planned to add 220R termination resistors (to ground) as these make a very significant improvement to the signal quality. Especially when fed from Phill's Atom Colour board.
