### ISSUE TITLE
Bug: Crash when double height buffer selected with >=325 line buffers

### ISSUE THREAD

**Issue by IanSB** [hoglet67/RGBtoHDMI#60]
If the buffer is >= 325 lines high there is a crash when double height selected (i.e make buffer 672x 650). Perhaps there is insufficient memory allocated for such large buffers?

**Comment by hoglet67** [comment]
What does the logging output from init_framebuffer() look like for 324 (working) and 325 (crashes)?

Does it still crash if NBUFFERS in defs.h is reduced from 4 to 3?

**Comment by hoglet67** [comment]
Most likely this bug is also fixed now. Can you test and close?

**Comment by IanSB** [comment]
Yes this is fixed by the above commit.
