### ISSUE TITLE
Configurable button actions

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#66]
Add support for detecting long and short button presses:
- A short button press action could happen on release
- A long button press action could happen on the "long press detection" timeout

Make the binding of the various actions to buttons configurable.

Actions would be:
- menu launch
- hdmi calibration (i.e. genlock)
- auto calibration (i.e. sampling clock calibration)
- take screen shot

Any others?

This would fix #49

**Comment by IanSB** [comment]
scanlines on / off
interpolation on / off
(or maybe a combination of the two on a single button)
NTSC artifacting on / off

**Comment by hoglet67** [comment]
This is now implemented.

Feel free to add additional actions - there are three palace holders (A5_SPARE, A6_SPARE, A7_SPARE)
