### ISSUE TITLE
Detect missing VSYNC and show a blank screen

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#7]
Ian suggested this based on his experience of the ZX80, which stops generating Sync when it's busy.

The wait_for_vsync code would need to be adapted with a timeout (how long?)

Dave

**Comment by hoglet67** [comment]
This is now pretty much done.

The only other thing I would like to have is an option to active the OSD to show the no sync detected warning. I'll leave this open for now.

**Comment by IanSB** [comment]
This has been addressed in the latest release:
https://github.com/hoglet67/RGBtoHDMI/releases/tag/20200504_d19df1c
