### ISSUE TITLE
Use labels in issues

### ISSUE THREAD

**Issue by hoglet67** [hoglet67/RGBtoHDMI#80]
I'd suggest staring with the following:

- feature
- improvement
- bug

There's a reasonable initial list already set up (click the wheel icon next to labels)

**Comment by hoglet67** [comment]
I'd suggest staring with the following:
- feature
- improvement
- bug

**Comment by IanSB** [comment]
I don't seem to be able to set labels.

**Comment by hoglet67** [comment]
I've added you as a collaborator, so (once you accept the permission), you should be able to set labels.

**Comment by hoglet67** [comment]
I'm going to get more time to work on this next week, so I've added:
- in progress (Ian)
- in progress (Dave)

If you have an intent to work on an issue, please label it with your "in progress" label, so that we don't end up working on the same things!
